import type { Metadata } from 'next';
import Hero from '@/components/Hero';
import { AccessHeroAnimation } from '@/components/HeroAnimations';
import ScrollReveal from '@/components/ScrollReveal';

export const metadata: Metadata = {
  title: 'Access | DARSAL',
  description: 'Professional trading desks operate under very different conditions than retail traders. Through DARSAL, those same conditions are now available.',
  openGraph: { images: ['/og-image.png'] },
};

export default function AccessPage() {
  return (
    <>
      <Hero
        label="EURUSD All-In Spread"
        displayNumber="0.6 Pip"
        headline="Institutional Spread Conditions"
        subheadline="Not marketing. Real trading conditions."
        rightContent={<AccessHeroAnimation />}
      />

      {/* Intro */}
      <section className="py-20 md:py-28 bg-bg-primary">
        <div className="mx-auto max-w-text px-6">
          <ScrollReveal>
            <p className="text-base text-charcoal leading-body">
              Professional trading desks — hedge funds, institutional desks, currency market specialists — operate under very different conditions than retail traders. Through the volume generated by DARSAL over many years, we&apos;ve negotiated those same conditions and made them available to selected independent traders.
            </p>
          </ScrollReveal>
        </div>
      </section>

      {/* What's Included */}
      <section className="py-20 md:py-28 bg-white">
        <div className="mx-auto max-w-text px-6">
          <ScrollReveal>
            <h2 className="text-2xl md:text-[28px] font-medium text-charcoal leading-heading tracking-heading mb-12">
              What&apos;s Included
            </h2>
            <ul className="space-y-6">
              {[
                'No additional commissions',
                'Execution through established broker infrastructure used by professional market participants',
                'No stop level, no freeze level — trading without artificial barriers',
                '0.5 pip available once monthly traded volume exceeds EUR 1 billion',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-4">
                  <span className="mt-1 shrink-0 w-5 h-5 rounded-full border border-gold flex items-center justify-center">
                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                      <path d="M2.5 6L5 8.5L9.5 4" stroke="#C9A96E" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                  </span>
                  <p className="text-base text-charcoal leading-body">{item}</p>
                </li>
              ))}
            </ul>
          </ScrollReveal>
        </div>
      </section>

      {/* Who This Is For */}
      <section className="py-20 md:py-28 bg-bg-primary">
        <div className="mx-auto max-w-text px-6">
          <ScrollReveal>
            <h2 className="text-2xl md:text-[28px] font-medium text-charcoal leading-heading tracking-heading mb-8">
              Who This Is For
            </h2>
            <p className="text-base text-charcoal leading-body">
              Experienced traders managing their own capital who are tired of paying retail spreads for institutional-grade strategies. If execution conditions are the difference between profitability and breakeven for you, this is what you&apos;ve been looking for.
            </p>
          </ScrollReveal>
        </div>
      </section>

      {/* Ghost CTA */}
      <section className="py-20 md:py-28 bg-white">
        <div className="mx-auto max-w-content px-6 text-center">
          <ScrollReveal>
            <a
              href="mailto:contact@darsal.net"
              className="inline-block border border-gold text-gold rounded-[2px] px-7 py-3 text-sm tracking-[0.5px] font-inter font-medium hover:bg-gold hover:text-navy-deep transition-all duration-200"
            >
              Sign Up
            </a>
          </ScrollReveal>
        </div>
      </section>
    </>
  );
}
