import type { Metadata } from 'next';
import Hero from '@/components/Hero';
import { AccessHeroAnimation } from '@/components/HeroAnimations';
import ScrollReveal from '@/components/ScrollReveal';

export const metadata: Metadata = {
  title: 'Access | DARSAL',
  description: 'Professional trading desks operate under very different conditions than retail traders. Through DARSAL, those same conditions are now available.',
  openGraph: { images: ['/og-image.png'] },
};

export default function AccessPage() {
  return (
    <>
      <Hero
        label="EURUSD All-In Spread"
        displayNumber="0.6 Pip"
        headline="Institutional Spread Conditions"
        subheadline="Not marketing. Real trading conditions."
        rightContent={<AccessHeroAnimation />}
      />

      {/* Intro */}
      <section className="py-20 md:py-28 bg-bg-primary">
        <div className="mx-auto max-w-text px-6">
          <ScrollReveal>
            <p className="text-base text-charcoal leading-body">
              Professional trading desks — hedge funds, institutional desks, currency market specialists — operate under very different conditions than retail traders. Through the volume generated by DARSAL over many years, we&apos;ve negotiated those same conditions and made them available to selected independent traders.
            </p>
          </ScrollReveal>
        </div>
      </section>

      {/* What's Included */}
      <section className="py-20 md:py-28 bg-white">
        <div className="mx-auto max-w-text px-6">
          <ScrollReveal>
            <h2 className="text-2xl md:text-[28px] font-medium text-charcoal leading-heading tracking-heading mb-12">
              What&apos;s Included
            </h2>
            <ul className="space-y-6">
              {[
                'No additional commissions',
                'Execution through established broker infrastructure used by professional market participants',
                'No stop level, no freeze level — trading without artificial barriers',
                '0.5 pip available once monthly traded volume exceeds EUR 1 billion',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-4">
                  <span className="mt-1 shrink-0 w-5 h-5 rounded-full border border-gold flex items-center justify-center">
                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                      <path d="M2.5 6L5 8.5L9.5 4" stroke="#C9A96E" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                  </span>
                  <p className="text-base text-charcoal leading-body">{item}</p>
                </li>
              ))}
            </ul>
          </ScrollReveal>
        </div>
      </section>

      {/* Who This Is For */}
      <section className="py-20 md:py-28 bg-bg-primary">
        <div className="mx-auto max-w-content px-6">
          <ScrollReveal>
            <div className="bg-white border border-border-light rounded-lg p-8 md:p-10 shadow-[0_1px_3px_rgba(0,0,0,0.08)]">
              <div className="grid md:grid-cols-[auto_1fr] gap-8 items-start">
                <svg width="80" height="80" viewBox="0 0 80 80" fill="none" className="offer-icon shrink-0" aria-hidden="true">
                  {/* Person */}
                  <circle cx="34" cy="22" r="10" stroke="#C9A96E" strokeWidth="1.5" fill="rgba(201,169,110,0.06)" />
                  <path d="M16 56C16 44 24 36 34 36C44 36 52 44 52 56" stroke="#C9A96E" strokeWidth="1.5" fill="none" strokeLinecap="round" />
                  {/* Terminal screen */}
                  <rect x="44" y="12" width="28" height="22" rx="3" stroke="#C9A96E" strokeWidth="1.5" fill="rgba(201,169,110,0.08)" />
                  <polyline points="50,20 54,24 58,18 62,22 66,19" stroke="#C9A96E" strokeWidth="1" fill="none" strokeLinecap="round" strokeLinejoin="round" />
                  <line x1="50" y1="28" x2="66" y2="28" stroke="rgba(201,169,110,0.3)" strokeWidth="1" strokeLinecap="round" />
                  {/* Chart bars */}
                  <rect x="50" y="42" width="5" height="14" rx="1" fill="rgba(201,169,110,0.15)" stroke="rgba(201,169,110,0.4)" strokeWidth="0.75" />
                  <rect x="58" y="38" width="5" height="18" rx="1" fill="rgba(201,169,110,0.2)" stroke="rgba(201,169,110,0.4)" strokeWidth="0.75" />
                  <rect x="66" y="44" width="5" height="12" rx="1" fill="rgba(201,169,110,0.15)" stroke="rgba(201,169,110,0.4)" strokeWidth="0.75" />
                  {/* Base line */}
                  <line x1="14" y1="64" x2="74" y2="64" stroke="rgba(201,169,110,0.2)" strokeWidth="1" />
                </svg>
                <div>
                  <h2 className="text-2xl md:text-[28px] font-medium text-charcoal leading-heading tracking-heading mb-4">
                    Who This Is For
                  </h2>
                  <p className="text-base text-charcoal leading-body mb-6">
                    Experienced traders managing their own capital who are tired of paying retail spreads for institutional-grade strategies. If execution conditions are the difference between profitability and breakeven for you, this is what you&apos;ve been looking for.
                  </p>
                  <div className="flex flex-wrap gap-3">
                    <span className="inline-block border border-gold/30 text-gold text-xs font-mono px-3 py-1.5 rounded-full">
                      Manages own capital
                    </span>
                    <span className="inline-block border border-gold/30 text-gold text-xs font-mono px-3 py-1.5 rounded-full">
                      Execution-sensitive strategies
                    </span>
                    <span className="inline-block border border-gold/30 text-gold text-xs font-mono px-3 py-1.5 rounded-full">
                      Institutional-grade requirements
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </ScrollReveal>
        </div>
      </section>

      {/* Ghost CTA */}
      <section className="py-20 md:py-28 bg-white">
        <div className="mx-auto max-w-content px-6 text-center">
          <ScrollReveal>
            <a
              href="mailto:contact@darsal.net"
              className="inline-block border border-gold text-gold rounded-[2px] px-7 py-3 text-sm tracking-[0.5px] font-inter font-medium hover:bg-gold hover:text-navy-deep transition-all duration-200"
            >
              Sign Up
            </a>
          </ScrollReveal>
        </div>
      </section>
    </>
  );
}
